# paths to ignore
ignore:
  - ".github/"
  - "ada_uea_experiments/"
  - "docs/"
  - "notebooks/"
  - "results/"
  - "tsml_eval/_wip/"

# PR status check
coverage:
  status:
    project:
      default:
        # treshold: 1%
        informational: true
    patch:
      default:
        informational: true

# post coverage report as comment on PR
comment: false

# enable codecov to report to GitHub status checks
github_checks:
  annotations: false
